/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
 /*\title MULTICAN data transmission
 * \abstract MULTICAN is used to exchange data between two nodes, implemented in the same device using Loop-Back mode.
 * \description A CAN message is sent from CAN node 0 to CAN node 1 using Loop-Back mode.
 *              After the CAN message transmission, an interrupt will be generated and LED1 will
 *              be turned on to confirm successful message transmission. Once the CAN message
 *              is successfully received by the CAN node 1, an interrupt will be generated.
 *              Inside the interrupt service routine the content of the received CAN message will be
 *              compared to the content of the transmitted CAN message. In case of a success, LED2
 *              will be turned on to confirm successful message reception.
 *
 * \name MULTICAN_1_KIT_TC275_LK
 * \version V1.0.0
 * \board AURIX TC275 lite Kit, KIT_AURIX_TC275_LITE, TC27xTP_D-Step
 * \keywords AURIX, CAN, MULTICAN, MULTICAN_1
 * \documents https://www.infineon.com/aurix-expert-training/Infineon-AURIX_MULTICAN_1_KIT_TC275_LK-TR-v01_00_00-EN.pdf
 * \documents https://www.infineon.com/aurix-expert-training/TC27D_iLLD_UM_1_0_1_12_0.chm
 * \lastUpdated 2021-06-29
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "Can.h"
#include "ASCLIN_Shell_UART.h"
#include "Motor_Driver.h"
#include "My_Itoa.h"
#include "Driver_Stm.h"

IfxCpu_syncEvent g_cpuSyncEvent = 0;
Message_Info test;

int core0_main(void)
{
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    initShellInterface();
    Ifx_Console_print("\r\n--------Start Transmission-----\r\n");
    init_can();
    initMotor();
    Driver_Stm_Init();
    setMotorDuty(0, 0);

    while(1)
    {
//        AppScheduling();
        Car_Control(Forward_straight, 0);
//        transmit_message(&g_MessageInfo, VEHICLE_STATUS_ID);
//        for(int i=0; i<200000000; i++) {}
    }
    return (1);
}


#if 0
typedef struct
{
    uint32 u32nuCnt1ms;
    uint32 u32nuCnt10ms;
    uint32 u32nuCnt100ms;
    uint32 u32nuCnt1000ms;
}TestCnt;

// Task scheduling related
void AppScheduling(void);
void AppTask1ms(void);
void AppTask10ms(void);
void AppTask100ms(void);
void AppTask1000ms(void);

TestCnt stTestCnt;

long current_enc_count = 0;
long currentRPM = 0;
long delta = 0;
long ulPGain = 2;
long ulIGain = 2;
long ulRpmRef = 0;
long g_nControlInput = 0;
long prev_enc_count = 0;
long duty = 0;
long g_nError = 0;
void MotorFeedbackController(void)
{
    static long lProportionalControlInput = 0;
    static long lIntegralControlInput = 0;
    static long lIntegralControlOld = 0;
    static uint32 ulSamplingFrequency = 10u; /*100ms*/

    g_nError = 0;
    g_nControlInput = 0;

    current_enc_count = abs(Get_Encoder_Value(1));
    delta = current_enc_count - prev_enc_count; // 이게 100ms 간격 누적 변화
    currentRPM = ((float32)delta * 60.0f * 10.0f) / (8.0f * 120.0f);
    prev_enc_count = current_enc_count;

    /*PID Controller*/
    g_nError = (long)getTargetRpm() - (long)currentRPM;
    lProportionalControlInput = ((long)ulPGain * g_nError / 10); // Note: gain is expressed as gain/10

    lIntegralControlInput = lIntegralControlOld + (((long)ulIGain * g_nError) / ((long)ulSamplingFrequency / 10));
    g_nControlInput = lProportionalControlInput + lIntegralControlInput; // PID control input

    lIntegralControlOld = lIntegralControlInput;

    if (lIntegralControlOld > 80u)
    {
        lIntegralControlOld = 80u; // Limit accumulated value by I gain
    }
    else if(lIntegralControlOld == 0u)
    {
        lIntegralControlOld = 0u;
    }

    if (g_nControlInput >= 80u)
    {
        g_nControlInput = 80u; // Limit control input (0 <= input < 100)
    }
    else if (g_nControlInput <= 0u)
    {
        g_nControlInput = 0u;
    }
    else
    {
        /* No Code */
    }

    if (getTargetRpm() == 0 || g_nControlInput == 0)
    {
        duty = 0;  // 완전 정지
    }
    else
    {
        // 동작 가능한 최소 duty부터 스케일링 (예: 65~100)
        duty = 65 + ((g_nControlInput * 35) / 100);
    }

    setMotorDuty(duty, duty);  // 좌우 모터에 동일 duty 적용
}


void AppTask1ms(void)
{
    stTestCnt.u32nuCnt1ms++;
}

void AppTask10ms(void)
{
    stTestCnt.u32nuCnt10ms++;

}

void AppTask100ms(void)
{
    stTestCnt.u32nuCnt100ms++;
    MotorFeedbackController();
    Ifx_Console_print("Test 100ms\r\n");
}

void AppTask1000ms(void)
{
    stTestCnt.u32nuCnt1000ms++;
}

void AppScheduling(void)
{
    if(stSchedulingInfo.u8nuScheduling1msFlag == 1u)
    {
        stSchedulingInfo.u8nuScheduling1msFlag = 0u;
        AppTask1ms();

        if(stSchedulingInfo.u8nuScheduling10msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling10msFlag = 0u;
            AppTask10ms();
        }

        if(stSchedulingInfo.u8nuScheduling100msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling100msFlag = 0u;
            AppTask100ms();
        }
        if(stSchedulingInfo.u8nuScheduling1000msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling1000msFlag = 0u;
            AppTask1000ms();
        }
    }
}
#endif

