/**********************************************************************************************************************
 * \file GTM_TOM_PWM.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the
 *company in which ordinary course of business you are acting and (ii) Infineon
 *Technologies AG or its licensees. If and as long as no such terms of use are
 *agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 *obtaining a copy of the software and accompanying documentation covered by
 *this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 *and to permit third-parties to whom the Software is furnished to do so, all
 *subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 *the above license grant, this restriction and the following disclaimer, must
 *be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 *solely in the form of machine-executable object code generated by a source
 *language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 *SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 *ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 *ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 *DEALINGS IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef MOTOR_H_
#define MOTOR_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "Ifx_Types.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

#define PWM_PERIOD 50000

#define MOTOR_L_PWM   IfxGtm_TOM0_9_TOUT1_P02_1_OUT // PIN3
#define MOTOR_L_BRAKE &MODULE_P02, 7 // PIN9
#define MOTOR_L_DIR   &MODULE_P10, 1 // PIN12

#define MOTOR_L_ENC_A &MODULE_P00, 4 // PIN33
#define MOTOR_L_ENC_B &MODULE_P14, 1 // PIN23

#define MOTOR_R_PWM   IfxGtm_TOM2_11_TOUT105_P10_3_OUT // PIN11
#define MOTOR_R_BRAKE &MODULE_P02, 6 // PIN8
#define MOTOR_R_DIR   &MODULE_P10, 2 // PIN13

#define MOTOR_R_ENC_A &MODULE_P14, 0 // PIN15
#define MOTOR_R_ENC_B &MODULE_P15, 6 // PIN42

#define ISR_PRIORITY_TOM     20
#define ISR_PRIORITY_L_ENC_A 10
#define ISR_PRIORITY_L_ENC_B 11
#define ISR_PRIORITY_R_ENC_A 12
#define ISR_PRIORITY_R_ENC_B 13

// Car Control
#define Forward_straight  0
#define Backward_straight 1
#define Forward_left      2
#define Forward_right     3
#define Backward_left     4
#define Backward_right    5
#define HOLD              6

#define ACW IfxPort_State_low
#define CW  IfxPort_State_high

/*********************************************************************************************************************/
/*-----------------------------------------------Function
 * Prototypes-------------------------------------------------*/
/*********************************************************************************************************************/

void initMotor(void);
int  Get_Encoder_Value(boolean LorR);
void Car_Control(uint8 mode, uint32 value);
void setMotorDuty(uint32 leftDuty, uint32 rightDuty);

#endif /* MOTOR_H_ */
